name: publish

on:
  schedule:
    - cron: '0 12 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        ref: master
    - name: binsh
      run: /bin/sh autocheck.sh
    - name: push
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.PUSH_TOKEN }}
        push-branch: 'master'
        commit-message: 'arr you code leetcode today?'
        force-add: 'true'
        files: README.md
        name: Dcell
        email: 765736477@qq.com 
